# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2023 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 eclips_e <67359748+Just-a-Unity-Dev@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 faint <46868845+ficcialfaint@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2026 Polonium-bot <admin@ss14.pl>
# SPDX-FileCopyrightText: 2026 nikitosych <174215049+nikitosych@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/_Polonium/Guidebook/Security/Security.xml"
  children:
  - Forensics
  - Defusal
  - CriminalRecords
  - RulesOfConduct # Funkystation
  - SpaceLaw # Goobstation

- type: guideEntry
  id: Forensics
  name: guide-entry-forensics
  text: "/ServerInfo/_Polonium/Guidebook/Security/Forensics.xml"

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/_Polonium/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: CriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/_Polonium/Guidebook/Security/CriminalRecords.xml"
