# SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 nikitosych <boriszyn@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2026 Damian Zieli≈Ñski <zientasek.pl@gmail.com>
# SPDX-FileCopyrightText: 2026 Nikita (Nick) <174215049+nikitosych@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 Polonium-bot <admin@ss14.pl>
# SPDX-FileCopyrightText: 2026 nikitosych <174215049+nikitosych@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 3600 # 1 hour

- type: jobRequirementOverride
  id: Zeroed
  jobs:
    Captain:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    HeadOfPersonnel:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    AtmosphericTechnician:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    ChiefEngineer:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    StationEngineer:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    TechnicalAssistant:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    MedicalIntern:
    - !type:OverallPlaytimeRequirement
      time: 0
    MedicalDoctor:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Paramedic:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Psychologist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chemist:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    ChiefMedicalOfficer:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    SecurityOfficer:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    SecurityCadet:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Brigmedic:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    HeadOfSecurity:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Detective:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Warden:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    ResearchAssistant:
    - !type:OverallPlaytimeRequirement
      time: 0
    Scientist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Roboticist:
    - !type:OverallPlaytimeRequirement
      time: 0
    ResearchDirector:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Borg:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    StationAi:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Boxer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Janitor:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chef:
    - !type:OverallPlaytimeRequirement
      time: 0
    Botanist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Quartermaster:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    CargoTechnician:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    SalvageSpecialist:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hour
    Bartender:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chaplain:
    - !type:OverallPlaytimeRequirement
      time: 0
    Clown:
    - !type:OverallPlaytimeRequirement
      time: 0
    Mime:
    - !type:OverallPlaytimeRequirement
      time: 0
    Lawyer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Librarian:
    - !type:OverallPlaytimeRequirement
      time: 0
    Musician:
    - !type:OverallPlaytimeRequirement
      time: 0
    ServiceWorker:
    - !type:OverallPlaytimeRequirement
      time: 0
    Zookeeper:
    - !type:OverallPlaytimeRequirement
      time: 0
    InternalAffairsAgent:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hours
    Magistrate:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    NanotrasenRepresentative:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
