on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  update-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Filter .ftl files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            ftl:
              - '**/*.ftl'

      - name: Skip if no .ftl files
        if: steps.filter.outputs.ftl != 'true'
        run: echo "No .ftl" && exit 78

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: polonium14/polonium-space
          ref: master
          submodules: recursive
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"

      - name: Restore and build
        run: |
          dotnet restore .github/update-translate-checklist/update-translate-checklist.csproj
          dotnet build   .github/update-translate-checklist/update-translate-checklist.csproj --configuration Release

      - name: Run
        run: bash .github/update-translate-checklist/run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_ID: ${{ github.repository_id }}
          BRANCH_NAME: main
